// <auto-generated />
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20231127143012_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Test description 1",
                            ImgUri = "D:\\images\\test",
                            Name = "Test product 1",
                            Price = 1000m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Test description 2",
                            ImgUri = "D:\\images\\test",
                            Name = "Test product 2",
                            Price = 3m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Test description 3",
                            ImgUri = "D:\\images\\test",
                            Name = "Test product 3",
                            Price = 59870m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Test description 4",
                            ImgUri = "D:\\images\\test",
                            Name = "Test product 4",
                            Price = 548m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Test description 5",
                            ImgUri = "D:\\images\\test",
                            Name = "Test product 5",
                            Price = 213m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Test description 6",
                            ImgUri = "D:\\images\\test",
                            Name = "Test product 6",
                            Price = 6000m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Test description 7",
                            ImgUri = "D:\\images\\test",
                            Name = "Test product 7",
                            Price = 1123m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
